# Generated by Django 2.2.5 on 2019-10-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testovac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
