# Generated by Django 2.2.6 on 2019-11-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark1', '0005_auto_20191024_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='domacnost',
            name='co2',
            field=models.CharField(default=400, max_length=150),
            preserve_default=False,
        ),
    ]
